title: PHP-Badges Documentation
description: This is the official PHP-Badges Documentation.
theme: just-the-docs

url: https://jmcrafter26.github.io/php-badges

aux_links:
  Download: https://github.com/JMcrafter26/php-badges/releases/latest
