title: PHP-Badges Docs
description: The official documentation of PHP-Badges
theme: just-the-docs

url: https://jmcrafter26.github.io/php-badges/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
