title: PHP-Badges Documentation
description: This is the official PHP-Badges Documentation.
theme: just-the-docs

url: https://jmcrafter26.github.io/php-badges

aux_links:
  Github: https://github.com/JMcrafter26/php-badges
  Download PHP-Badges: https://github.com/JMcrafter26/php-badges/releases/latest

plugins:
  - jekyll-image-size
