title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://jmcrafter26.github.io/php-badges

aux_links:
  Download: https://github.com/JMcrafter26/php-badges/releases/latest
